version: '3.8'

services:
  portal:
    image: registry.gitlab.com/k-security/portal-react:latest
    env_file: .env
    ports:
      - '${PORT}:80'
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5
